### PR TITLE
#221 add list support to ModelWrapper

### PR DESCRIPTION
**Pull request by lihop**
An initial attempt at adding list support to the ModelWrapper.

In order to be consistent with other commit messages, I had #221 in the commit message. However, this was causing notifications to be added to the issue tracker whenever I made modifications to the commits, so I removed it from the message.

### CODE REVIEW

**Comment by manuel-mauky** [comment]
The notifications in the issue tracker are no problem at all ;-)

**Comment by manuel-mauky** [comment]
I've reviewed your pull request and it looks really good.

The only part that wasn't correct in my opinion was the `isDifferent` methods in both the `BeanListPropertyField` and `FxListPropertyField` classes. You had this code:

``` java
public boolean isDifferent(M wrappedObject) {
    final List<E> modelValue = accessor.apply(wrappedObject).getValue();
    final List<E> wrapperValue = targetProperty;

    return !(modelValue.containsAll(wrapperValue) && wrapperValue.containsAll(modelValue));
}
```

The condition isn't correct in my opinion because `List` can contain duplicate values which you can't find this way. Consider a case where `modelValue` has the content `["somestring", "somestring"]` and `wrapperValue` has the content `["somestring"]`. In this case the method will still say that both lists aren't different.
The second problem with this implementation is that when either the model or wrapped list is `null` we will get a `NullPointerException`.

I've changed it to `!Objects.equals(modelValue, wrapperValue)` like in the other classes. Looking at the [JavaDoc of List](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#equals-java.lang.Object-) it says that using the `equals` method is perfectly fine to determine if two lists have the same content.

The question is: Do I miss something? Did you had a specific intention with your code or was it by mistake? 

Nevertheless: Great job and many thanks for your contribution.

**Comment by lihop** [comment]
Hi Manuel,

You are correct that `isDifferent` should be using the `equals` method. This was a mistake on my part. Perhaps I was confusing `equals` with `==`.

Regardless: thank you for taking the time to review this pull request.

**Comment by lihop** [comment]
Just a quick question. Do I need to do anything further (e.g. incorporate your changes into the pull request) or will you take it from here?

**Comment by manuel-mauky** [comment]
No you don't need to do anything further. 
I've done my changes on the same pull request branch so that they are all in one place. I will now merge this branch into the main development branch and that's all.

**Pull request merged**
