### PR TITLE
#342

### PR DESCRIPTION
**Pull request by Naoghuman**
Discussed points which are implemented:
- Add missing suffix (View, ViewModel) to classes.
- Format all example projects which will be relevant for the plugin.

Although I see that the functionality in the contact example isn't ready implemented. I can't edit, delete or add new contacts there. Perhaps a new issue should be filled for the missing implementation.

Peter

### CODE REVIEW

**Comment by manuel-mauky** [comment]
Sorry for the late response.
In #342 we have discussed to use a single tab for indentation and that you will replace double tabs with a single one. But in this PR you have replaces tabs with 4 spaces each?

**Comment by Naoghuman** [comment]
Hi lestard,
in NetBeans is default preference that a `tab` is extended to `4 spaces`. So when I press the tab key in editor then 4 spaces will be insert.

When thats not okay for you, then I can refactore the files. I see, that I can export and import the preferences (because I use in all my other project the default behaivour tab=4spaces) so that I must in future changing the preferences (develop this project = preferencesA, all other projects = preferencesB).

**Comment by manuel-mauky** [comment]
I think we should keep the single tab character instead of 4 Spaces as it's the code style already used in the project (at least in most files).

**Comment by Naoghuman** [comment]
I change like said the 4 spaces in one tab indentation.

**Comment by manuel-mauky** [comment]
Now the PR looks great.

p.s. sorry for the delay.

**Pull request merged**
