### PR TITLE
Early return in calculateDifferenceFlag()

### PR DESCRIPTION
**Pull request by johnp**
Classic for-each seems to be a better approach than the Streams-API here. Allows early return and prevents new collection creation in the filter()-call.

I've refactored the ModelWrapper into a Kotlin-native implementation and would like to contribute it to the tornadoFX project (also Apache 2.0 licensed).
From what I've read about the licensing terms it's enough if I keep the original copyright notice at the top of the file? The Kotlin-implemenation doesn't need the accessorfunctions package and relies on higher-order functions instead.

### CODE REVIEW

**Comment by manuel-mauky** [comment]
Hi Johannes, 
thanks for your PR. Your are correct about the for loop.

For me it's perfectly fine if you contribute the ModelWrapper to tornadoFX. To be licence conforming you simply need to keep the licence header in the file. 
I would be happy if you could also mention the mvvmFX project in the javadoc so that people using the ModelWrapper in tornadoFX know where the class comes from.

**Comment by johnp** [comment]
Of course, happy to do so ;)
Still have some cleaning up to do and provide examples and tests, but will CC you on the final PR once it's submitted.

**Comment by sialcasa** [comment]
@johnp can you please contribute fixes / extensions of your fork back to our repo?

**Comment by johnp** [comment]
@sialcasa Sure, but for now it's mostly just been converting types to Kotlin-native ones, so that calls from Kotlin are easier and some minor adjustments here and there to use some Kotlin-specific functionality. 
One thing for example is, that Kotlin currently cannot fully infer lambda types based on their return type and therefore cannot choose an overloaded function, which means, in my experience, sometimes having to manually cast the type[[1](https://discuss.kotlinlang.org/t/higher-order-function-overload-ambiguity/1702)]. [SAM conversions](http://kotlinlang.org/docs/reference/java-interop.html#sam-conversions) for accessorfunctions require quite a bit of code, so that one may has to write something like this `var name = wrapper.field(StringGetter { p: Person -> p.name }, StringSetter { p: Person, v: String -> p.name = v })` for simple class variables. On the other hand, sometimes Kotlin can infer types better than the JVM, which allows more aggressive overloading by using the [@JvmName](http://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/-jvm-name/) annotation, although I got rid of most of those by now.
It's mainly the strict type system and the custom accessorfunction classes vs Kotlin native higher order functions and Kotlin properties that make interaction with the original java implementation require more code than what should be necessary.
With Kotlin's [KProperty1](http://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/-k-property1/index.html)/[KMutableProperty1](http://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/-k-mutable-property1/index.html) types (simply any `val` or `var` of a class) adding a field now just becomes `val name = wrapper.field(Person::name)`

Regarding extensions, I have to admit that right now I don't really miss anything. The whole ModelWrapper concept is very good designed and doesn't have any dependencies to other parts of mvvmFX. Really the only bug I encountered was the one call missing its defaultValue. Kudos for such a nice, clean design & implementation.

**Comment by manuel-mauky** [comment]
As you are mentioning SAM and Lambda conversion in kotlin I have a question on this topic.
In the ModelWrapper we have overloaded `field` methods that are taking a string identifier as first argument because in java a lambda or a method reference itself can't be used as identifier/key in a Map because it is not `equals` to itself:

``` java
Supplier<String> a = Person::getName;
Supplier<String> b = Person::getName;

System.out.println(a.equals(b)); // -> false
```

Even though `a` and `b` are pointing to the same getter they aren't `equal` in Java. 

What is the behavior in Kotlin? If this works you could even skip the overloaded methods with the string identifier.

**Comment by johnp** [comment]
Thanks for the hint. I was already thinking about removing some of the getter/setter based overloaded `field` methods and rely on KProperty1/KMutableProperty1 completely, as it's probably the best way to add a field (not having to specify any type at all) and there's really no reason not to. This is apparently one more good reason to do that (see below) and together with skipping the identifier could also reduce the amount of code considerably.
It seems that Kotlin behaves similar in regards to its more primitive function types, but KProperty1/KMutableProperty1 looks good (`==` is a null-safe equals shorthand in Kotlin):

```
val a = Person::name
val b = Person::name
System.out.println(a == b) // -> true

val c = Person::name.getter
val d = Person::name.getter
System.out.println(c == d) // -> false

val e = Person::name.setter
val f = Person::name.setter
System.out.println(e == f) // -> false

val g = { s: Person -> s.name }
val h = { s: Person -> s.name }
System.out.println(g == h) // -> false

val i = { s: Person, v: String -> s.name = v }
val j = { s: Person, v: String -> s.name = v }
System.out.println(i == j) // -> false
```

Maybe you could use Java reflection to get equal objects or use the field name via reflection as key?

```
val getter1 = Person::class.java.getDeclaredMethod("getName")
val getter2 = Person::class.java.getDeclaredMethod("getName")
System.out.println(getter1 == getter2) // -> true

val setter1 = Person::class.java.getDeclaredMethod("setName", String::class.java)
val setter2 = Person::class.java.getDeclaredMethod("setName", String::class.java)
System.out.println(setter1 == setter2) // -> true

val field1 = Person::class.java.getDeclaredField("name")
val field2 = Person::class.java.getDeclaredField("name")
System.out.println(field1 == field2) // -> true
```

**Pull request merged**
